// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine.EventSystems;
namespace Nodeplay.Interfaces
{
		public interface Iinteractable
		{

              void OnDeselect(BaseEventData eventData);
              void OnDrag(PointerEventData eventData);
              void OnDrop(PointerEventData eventData);
              void OnMove(AxisEventData eventData);
              void OnPointerClick(PointerEventData eventData);
              void OnPointerDown(PointerEventData eventData);
              void OnPointerEnter(PointerEventData eventData);
              void OnPointerExit(PointerEventData eventData);
              void OnPointerUp(PointerEventData eventData);
              void OnScroll(PointerEventData eventData);
              void OnSelect(BaseEventData eventData);
              void OnUpdateSelected(BaseEventData eventData);
		}

}